name: Keycloak Repack
on:
  push:
    branches:
      - 'main'
permissions: write-all
env:
  NAME: keycloak
jobs:
  build:
    name: Publish to Github CR
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: List keys
        run: gpg -K
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependency
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
          working-directory: keywind
      - name: Vite Build
        run: npm run build:jar
        working-directory: keywind
      - name: Login to Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPOSITORY_PACKAGE_TOKEN }}
      - name: Buildah Build
        id: container-build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NAME }}
          tags: ${{ github.run_number }}
          containerfiles: |
            ./Containerfile
      - name: Buildah Push
        id: container-push
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          image: ${{ env.NAME }}
          tags: ${{ github.run_number }}
          extra-args: --sign-by moo@moo.is
      - name: Print image url
        run: echo "Image pushed to ${{ steps.container-push.outputs.registry-paths }}"
