name: Keycloak Repack
on:
  push:
    branches:
      - 'main'
permissions: write-all
env:
  NAME: keycloak
  CONTAINER: ghcr.io/moohouse/keycloak
  MANIFEST: keycloak/Rollout.yaml
jobs:
  build:
    name: Publish to Github CR
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js Version
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_PACKAGE }}
      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          trust_level: 5
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Buildah Build
        id: container-build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.NAME }}
          tags: ${{ github.run_number }}
          containerfiles: |
            ./Containerfile
      - name: Buildah Push
        id: container-push
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          image: ${{ env.NAME }}
          tags: ${{ github.run_number }}
          extra-args: --sign-by moo@moo.is
      - name: Print image url
        run: echo "Image pushed to ${{ steps.container-push.outputs.registry-paths }}"
      - name: Checkout Manifest
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 01
          repository: moohouse/manifest
          ref: main
          token: ${{ secrets.PAT_REPOSITORY }}
      - name: List keys
        run: gpg -K
      - name: Argo-CD Push
        run: |
          echo '${{ steps.import-gpg.outputs.email }}'
          echo '${{ steps.import-gpg.outputs.name }}'
          sed -i "s^${{ env.CONTAINER }}:[0-9]*^${{ env.CONTAINER }}:${{ github.run_number }}^g" ${{ env.MANIFEST }}
          git commit -am "Tag. ${{ github.run_number  }}"
          git remote set-url origin https://${{ github.repository_owner }}:${{ secrets.PAT_REPOSITORY }}@github.com/${{ github.repository_owner }}/manifest
          git push origin main
        shell: bash